name: WeRead Automation

on:
  schedule:
    - cron: '0 22 * * *'    # 北京时间22:00
    - cron: '0 5 * * *'     # 北京时间5:00
    - cron: '40 11 * * *'   # 北京时间11:40
    - cron: '0 17 * * 6,7'  # 周末17:00（周六/日）
    - cron: '0 8 * * 1'     # 周一8:00
    timezone: Asia/Shanghai  # ✅ 正确位置：在schedule列表内

  workflow_dispatch:
    inputs:
      mode:
        description: '运行模式'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - manual

jobs:
  generate-time:
    runs-on: ubuntu-22.04
    environment: Production

    steps:
    - name: 🛠️ 检出仓库
      uses: actions/checkout@v4

    - name: 🐍 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 📦 安装依赖
      run: pip install requests==2.32.3

    - name: ⏳ 动态延迟
      if: ${{ github.event_name == 'schedule' && inputs.mode != 'manual' }}
      run: |
        if [ $(date +%u) -eq 1 ] && [ $(date +%H) -eq 8 ]; then
          echo "⏩ 跳过周一延迟"
          exit 0
        fi
        DELAY=$((RANDOM % 21))
        echo "🕒 延迟 ${DELAY} 分钟"
        sleep ${DELAY}m

    - name: 🎯 生成阅读时长
      id: time-gen
      run: |
        if [[ "${{ inputs.mode }}" == "manual" ]]; then
          NUM=$((90 + RANDOM % 91))
        else
          case $(date +%H) in
            05|22) NUM=$((120 + RANDOM % 61)) ;;
            11)    NUM=$((120 + RANDOM % 61)) ;;
            17)    [ $(date +%u) -ge 6 ] && NUM=$((120 + RANDOM % 61)) || NUM=0 ;;
            08)    NUM=$((120 + RANDOM % 61)) ;;
            *)     echo "❌ 时间匹配错误"; exit 1 ;;
          esac
        fi
        echo "read_time=$NUM" >> $GITHUB_OUTPUT

    - name: 📤 输出结果
      if: ${{ steps.time-gen.outputs.read_time != 0 }}
      run: echo "✅ 生成成功：${{ steps.time-gen.outputs.read_time }}秒"
