name: wxread

on:
  schedule:
    - cron: '00 14 * * *'         # 北京22:00 UTC+8
    - cron: '0 21 * * *'          # 北京5:00
    - cron: '40 3 * * *'         # 北京11:40
    - cron: '0 9 * * sat,sun'    # 周末17:00
    - cron: '0 0 * * 1'          # 周一8:00
  workflow_dispatch:
    inputs:
      mode:
        description: '运行模式 (auto/manual)'
        required: false
        default: 'auto'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: AutoRead

    steps:
    - name: 🔧 设置DNS
      run: |
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf

    - name: 📥 检出仓库
      uses: actions/checkout@v4

    - name: 🐍 设置Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 📦 安装依赖
      run: |
        pip install requests==2.32.3

    # 仅定时任务执行延迟（排除周一任务和手动模式）
    - name: ⏱️ 随机延迟
      if: |
        github.event_name == 'schedule' &&
        github.event.schedule != '0 0 * * 1' &&
        github.event.inputs.mode != 'manual'
      run: |
        DELAY=$((RANDOM % 21))
        echo "🕒 延迟 $DELAY 分钟"
        sleep $(($DELAY * 60))

    # 周一随机检查（1/7概率）
    - name: 🎲 周随机检查
      if: github.event.schedule == '0 0 * * 1'
      run: |
        if [ $((RANDOM % 7)) -ne 0 ]; then
          echo "⏩ 跳过本周任务"
          exit 0
        fi

    # 动态生成阅读时长
    - name: 🔢 生成READ_NUM
      run: |
        if [[ "${{ github.event.inputs.mode }}" == "manual" ]]; then
          # 手动模式：90-180分钟（45-90分钟*2）
          NUM=$((90 + RANDOM % 91)) 
          echo "🛠️ 手动模式 READ_NUM=$NUM"
        else
          case "${{ github.event.schedule }}" in
            '0 21 * * *')   # 早间任务
              NUM=$((90 + RANDOM % 61)) ;; # 45-75分钟
            '40 3 * * *')   # 午间任务
              NUM=$((120 + RANDOM % 61)) ;;
            '00 14 * * *')  # 晚间任务
              NUM=$((120 + RANDOM % 61)) ;;
            '0 9 * * sat,sun') # 周末
              NUM=$((120 + RANDOM % 61)) ;;
            '0 0 * * 1')    # 周一任务
              NUM=$((120 + RANDOM % 121)) ;;
            *)              # 默认安全值
              NUM=$((120 + RANDOM % 61)) ;;
          esac
          echo "⏰ 定时模式 READ_NUM=$NUM"
        fi
        echo "READ_NUM=$NUM" >> $GITHUB_ENV

    - name: 🚀 执行主程序
      env:
        WXREAD_CURL: ${{ secrets.WXREAD_CURL }}
      run: |
        curl -X POST -d "read_num=$READ_NUM" "$WXREAD_CURL"
        echo "✅ 已提交阅读时长：$READ_NUM 分钟"
