name: wxread

on:
  schedule:
    - cron: '0 7 * * *'         # 早上7点
    - cron: '30 12 * * *'       # 中午12点半
    - cron: '0 20 * * *'        # 晚上8点
    - cron: '0 10 * * sat'      # 周六10点随机阅读
    - cron: '0 10 * * sun'      # 周日10点随机阅读
  workflow_dispatch:
    inputs:
      mode:
        description: '运行模式 (auto/manual)'
        required: false
        default: 'auto'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: AutoRead

    steps:
    - name: 🔧 设置DNS
      run: |
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf
        echo "✅ DNS配置完成"

    - name: 📥 检出仓库
      uses: actions/checkout@v4

    - name: 🐍 设置Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 📦 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install certifi==2024.8.30 charset-normalizer==3.4.0 idna==3.10 requests==2.32.3 urllib3==2.2.3
        echo "✅ 依赖安装验证：$(pip list | grep requests)"

    - name: ⏱️ 随机延迟
      if: github.event_name == 'schedule'
      run: |
        DELAY=$((RANDOM % 21))
        echo "生成的随机延迟：${DELAY}分钟"
        sleep $((DELAY * 60))
        echo "延迟执行完成"

    - name: 🔢 生成READ_NUM
      run: |
        # 调试信息
        echo "=== 触发事件分析 ==="
        echo "事件类型: ${{ github.event_name }}"
        echo "输入模式: ${{ github.event.inputs.mode }}"
        echo "定时规则: ${{ github.event.schedule }}"

        if [[ "${{ github.event.inputs.mode }}" == "manual" ]]; then
          # 手动模式
          NUM=$((RANDOM % 121 + 120))
          echo "🕹️ 手动模式 | 范围: 120-240 (60-120分钟)"
        else
          # 获取触发规则
          SCHEDULE="${{ github.event.schedule }}"

          case "$SCHEDULE" in
            '0 7 * * *')
              NUM=$((RANDOM % 21 + 60))   # 60-80分钟
              echo "🌅 早间任务 | 范围: 60-80" ;;
            '30 12 * * *')
              NUM=$((RANDOM % 21 + 40))  # 40-60分钟
              echo "🌞 午间任务 | 范围: 40-60" ;;
            '0 20 * * *')
              NUM=$((RANDOM % 21 + 100))  # 100-120分钟
              echo "🌙 晚间任务 | 范围: 100-120" ;;
            '0 10 * * sat')
            '0 10 * * sun')
              NUM=$((RANDOM % 121 + 120)) # 60-120分钟
              echo "🎉 周末任务 | 范围: 120-240" ;;
            *)
              # 安全模式：生成默认值
              NUM=$((RANDOM % 61 + 120))
              echo "⚠️ 未知触发类型 | 启用安全默认值: 120-180" ;;
          esac
        fi

        # 输出结果
        echo "✅ 最终READ_NUM: $NUM (等效 $((NUM / 2)) 分钟)"
        echo "READ_NUM=$NUM" >> $GITHUB_ENV

    - name: 🚀 执行主程序
      env:
        WXREAD_CURL_BASH: ${{ secrets.WXREAD_CURL_BASH }}
      run: |
        echo "=== 执行参数 ==="
        echo "READ_NUM: ${{ env.READ_NUM }}"
        python main.py
