name: WeRead Auto
on:
  schedule:
    - cron: '0 21 * * *'   # 北京时间5:00
    - cron: '40 3 * * *'    # 北京时间11:40 
    - cron: '0 14 * * *'    # 北京时间22:00
  workflow_dispatch:
    inputs:
      mode:
        description: '运行模式 (auto/manual)'
        required: false
        default: 'auto'

jobs:
  execute:
    runs-on: ubuntu-22.04
    environment: AutoRead
    env:
      B_VALUES: ${{ vars.B_VALUES }}       # 书籍ID列表
      PUSH_METHOD: ${{ vars.PUSH_METHOD }} # 推送方式
      WXREAD_CURL_BASH: ${{ secrets.WXREAD_CURL_BASH }}

    steps:
    # ----------------- 初始化阶段 -----------------
    - name: 🔧 DNS配置
      run: |
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf

    - name: 📥 代码检出
      uses: actions/checkout@v4
      with:
        path: main-repo

    # ---------------- 环境准备 --------------------
    - name: 🐍 Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: 📦 安装依赖
      working-directory: main-repo
      run: |
        pip install requests==2.32.3 python-dotenv==1.0.0
        echo "✅ 依赖安装完成"

    # ---------------- 执行控制 --------------------
    - name: ⏳ 随机延迟
      run: |
        DELAY=$(($RANDOM % 21))
        echo "🕒 延迟 ${DELAY} 分钟启动"
        sleep $(($DELAY * 60))

    - name: 🎲 生成动态参数
      id: params
      working-directory: main-repo
      run: |
        HOUR=$(date -u +%H)
        case $HOUR in
          21)   # 对应北京时间5:00
            READ_NUM=$((90 + $RANDOM % 41)) ;;  # 90-130次
          3)    # 对应北京时间11:40
            READ_NUM=$((120 + $RANDOM % 61)) ;; # 120-180次
          14)   # 对应北京时间22:00
            READ_NUM=$((180 + $RANDOM % 61)) ;; # 180-240次
          *)
            READ_NUM=150 ;;
        esac
        echo "READ_NUM=$READ_NUM" >> $GITHUB_ENV
        echo "生成阅读次数: $READ_NUM"

    - name: 🚀 执行任务
      working-directory: main-repo
      env:
        READ_NUM: ${{ env.READ_NUM }}
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      run: |
        python main.py
